# Config file for automatic testing at travis-ci.org
language: python

before_install:
 - sudo apt-get install -qq python-numpy python-scipy

python:
- "3.4"
- "3.3"
- "2.7_with_system_site_packages"
install:
- pip install coveralls
- pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script: coverage run --source hope setup.py test
after_success:
    coveralls
