# Config file for automatic testing at travis-ci.org
language: python

before_install:
  - sudo apt-get install -qq python-numpy python-scipy

python:
- "2.7_with_system_site_packages"

install:
- pip install coveralls
- pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script: coverage run --source abcpmc setup.py test
after_success:
    coveralls
